### ISSUE TITLE
julia compatibility requirements

### ISSUE THREAD

**Issue by RossBoylan** [kleinschmidt/RegressionFormulae.jl#8]
It looks as if Project.toml currently requires Julia 1.6.  Since 1.7 is out and 1.8 is coming, it would be good to loosen that.
https://github.com/kleinschmidt/RegressionFormulae.jl/blob/934aae9c7cfe1e613bd8d091506a99ee3b0344bc/Project.toml#L14

I don't know if any other changes are necessary to make it work with later Julias.

**Comment by palday** [comment]
The requirement is for the lowest compatible version, later 1.x Julia versions work just fine. The CI even tests against 1.6 (compat bound) and "1" (latest released version):

https://github.com/kleinschmidt/RegressionFormulae.jl/blob/934aae9c7cfe1e613bd8d091506a99ee3b0344bc/.github/workflows/CI.yml#L22-L23

(This is also in line with SemVer and [the way Julia manages compatibility entries](https://pkgdocs.julialang.org/v1/compatibility/).)

If you do run into a problem on 1.7 or 1.8, of course let us know!
